name: pandoc-build-and-publish

on: [push]

jobs: 
  pandoc-compile:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install pandoc
      # - run: pandoc --help
      - uses: actions/checkout@v2
      - run: ls ${{ github.workspace }}
